const $=id=>document.getElementById(id);let context=null,metadata={areas:[],tagsByArea:{},allTags:[]},selectedTags=[];const imageMode=new URLSearchParams(location.search).has('image');
function domainFrom(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''}}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setStatus(text,kind=''){$('status').textContent=text;$('status').className=`status ${kind}`}
async function getSettings(){return chrome.runtime.sendMessage({type:'GET_SETTINGS'})}
async function loadMetadata(endpoint,token){if(!endpoint||!token)return;try{const r=await fetch(endpoint,{headers:{'x-fetch-token':token}});if(!r.ok)return;metadata=await r.json();$('areaList').innerHTML=(metadata.areas||metadata.categories||[]).map(x=>`<option value="${esc(x)}"></option>`).join('');updateSuggestions()}catch{}}
function availableTags(){const area=$('area').value.trim();return (metadata.tagsByArea?.[area]?.length?metadata.tagsByArea[area]:metadata.allTags)||[]}
function renderTags(){$('tagChips').innerHTML=selectedTags.map(t=>`<span class="tag-chip">${esc(t)}<button data-remove="${esc(t)}" aria-label="Remove ${esc(t)}">×</button></span>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{selectedTags=selectedTags.filter(t=>t!==b.dataset.remove);renderTags();updateSuggestions()}))}
function addTag(raw){const tag=String(raw||'').trim().replace(/\s+/g,' ');if(!tag||selectedTags.some(t=>t.toLowerCase()===tag.toLowerCase()))return;selectedTags.push(tag);$('tagInput').value='';renderTags();updateSuggestions()}
function updateSuggestions(){const q=$('tagInput').value.trim().toLowerCase();const suggestions=availableTags().filter(t=>!selectedTags.includes(t)&&(!q||t.toLowerCase().includes(q))).slice(0,7);$('tagSuggestions').innerHTML=suggestions.map(t=>`<button data-suggest="${esc(t)}">${esc(t)}</button>`).join('');$('tagSuggestions').classList.toggle('show',!!suggestions.length&&document.activeElement===$('tagInput'));document.querySelectorAll('[data-suggest]').forEach(b=>b.addEventListener('mousedown',e=>{e.preventDefault();addTag(b.dataset.suggest)}))}
async function start(){const settings=await getSettings();loadMetadata(settings.endpoint,settings.captureToken);const result=await chrome.runtime.sendMessage({type:'GET_CAPTURE_CONTEXT',imageMode});if(result?.error){setStatus(result.error,'error');return}context=result;$('title').value=result.title||'';$('titlePreview').textContent=result.title||'Untitled page';$('domainPreview').textContent=domainFrom(result.url);$('type').value=result.captureType||'Page';if(result.screenshotDataUrl){const img=new Image();img.src=result.screenshotDataUrl;$('shot').appendChild(img)}else $('shot').textContent='No preview';if(result.selectedText){$('selectionWrap').classList.remove('hidden');$('selection').value=result.selectedText}if(result.imageUrl){$('imageWrap').classList.remove('hidden');$('imageUrl').value=result.imageUrl}if(result.pageDate)$('dateNote').textContent=`Page date detected: ${result.pageDate}`;setStatus('Ready to save.','good');$('area').focus()}
$('type').addEventListener('change',()=>{$('selectionWrap').classList.toggle('hidden',$('type').value!=='Text');$('imageWrap').classList.toggle('hidden',$('type').value!=='Image link')});$('area').addEventListener('input',updateSuggestions);$('tagInput').addEventListener('input',updateSuggestions);$('tagInput').addEventListener('focus',updateSuggestions);$('tagInput').addEventListener('blur',()=>setTimeout(()=>$('tagSuggestions').classList.remove('show'),120));$('tagInput').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===','){e.preventDefault();addTag($('tagInput').value)}else if(e.key==='Backspace'&&!$('tagInput').value&&selectedTags.length){selectedTags.pop();renderTags()}});$('options').addEventListener('click',()=>chrome.runtime.openOptionsPage());$('cancel').addEventListener('click',()=>window.close());$('save').addEventListener('click',async()=>{if(!context)return;addTag($('tagInput').value);const area=$('area').value.trim(),title=$('title').value.trim();if(!area||!title){setStatus('Title and area are required.','error');return}$('save').disabled=true;setStatus('Saving…');const payload={title,url:context.url,domain:domainFrom(context.url),area,category:area,tags:selectedTags,page_date:context.pageDate||null,capture_type:$('type').value,selected_text:$('type').value==='Text'?$('selection').value.trim()||null:null,image_url:$('type').value==='Image link'?$('imageUrl').value.trim()||null:null,screenshot_data_url:context.screenshotDataUrl||null};const result=await chrome.runtime.sendMessage({type:'SAVE_CAPTURE',payload});if(result?.needsSetup){setStatus('Open settings once to connect Fetch.','error');$('save').disabled=false;return}if(!result?.ok){setStatus(result?.error||'Could not save.','error');$('save').disabled=false;return}setStatus('✓ Saved to Fetch.','good');setTimeout(()=>window.close(),1250)});start();
